---
# Source: ks-core-outside-cluster/templates/ks-controller-manager.yaml
apiVersion: v1
data:
  ca.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lRT1laeGY5aVozRFJ6TGxkMDFoT3RtVEFOQmdrcWhraUc5dzBCQVFzRkFEQWoKTVNFd0h3WURWUVFERXhocmN5MWpiMjUwY205c2JHVnlMVzFoYm1GblpYSXRZMkV3SGhjTk1qRXdOakV3TURZMQpNRFF6V2hjTk16RXdOakE0TURZMU1EUXpXakFqTVNFd0h3WURWUVFERXhocmN5MWpiMjUwY205c2JHVnlMVzFoCmJtRm5aWEl0WTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURIWitxaE5xSFAKc3ZLSzFtUWlERlFNQlpkTkhhNitOT1J5UHBnc2hRcDhCbHBPRmpaWWJjQ0Y4YitnSzRTU1loOTVENzZXS3lPNwpZMXBjT1FpZXFMQ0x5S25OQXlvRlQ0VFVaZmswU0JaUHZsUmMwZ3FCS3FRNFZBak1TeVN3SGphaGdueDdOVkhNClZBQkN3aTR6enoyRE5KZ3J4aE5rU0VvMms1MmJiMmpPeWdVbmFydDdUYnl2V3JheEIreHpVQ3JKUjNSTi9raXUKS0pZUFBwZ1FkUlQxd284QzJlcGdOWWVvNUJ5WmNwWnVqbXFqbXNRR2lpU2s4SG9ZNUJ6eDdoOGRZQ3dDODVEMQpRK3NYTlJRMmRzY0ltcFVqek51TGZLV0FKMWNhSlFWaHQ0ZkJkWjdHZW5qazhCWUt5Mk1ueU1rOXlLcEcwK2F4CmpFMDRVTUhIMGdnSEFnTUJBQUdqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3IKQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVZjBnTQpOelk2VllYSzhTYysvU0Q2R0FETDVQUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSVRUQW9KR0FCeTBuMmpBCkdMazRMemhjMTUxalp5cGNsRFNqNGUxaUEvNG55V1I3dWUrWG1Jb25TbmI4dE9tSWM5VDZNMTJaWXczc0ZtcGoKNTMzdGZ6YUFQME5BZVA4VWFFZlIwZVFGU3lpYjYyeVYzZWlaOFhuWHJvNnNoRkNmbU8zU25pS3NjUnU5dEtBcgpkdzFZbWtleHRBei90YmkxM0tjekU2cHJMejFCbWk1TmtzcUJMS0VFc2ZFaXlRNEYyS1VGS3BHZmRLd05HSTIrCnRmUFQ4aG5vT0laM0xMZWhkemtSUUVST1JvYUtIcHVkcGIxcVptb0RjQXBSTGRIVzFWRTl2R1pFVUN4UmFIbzMKZFQ0aGlkZnllQ2ZuZWlSaEovWW8xNU4yd2NqTEpQbnBlRlRobEhFZUJEU1hOMGRnK0RIeW5XSE5pNHNSQ0JvYQpRS2NKcVo0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lSQUtOUmxBNUNadnhOTkRydktHZTNCWTB3RFFZSktvWklodmNOQVFFTEJRQXcKSXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0WVc1aFoyVnlMV05oTUI0WERUSXhNRFl4TURBMgpOVEEwTTFvWERUTXhNRFl3T0RBMk5UQTBNMW93S1RFbk1DVUdBMVVFQXhNZVVrVk1SVUZUUlMxT1FVMUZMV0ZrCmJXbHpjMmx2YmkxM1pXSm9iMjlyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEKMkFpNHg1cWNMMG5UcWsxVWx5SjNUSnd3emJTWGdEd1dRUHlVWU9jRWcxc3F5VmRaUFdXSjFtWXE2RXZlQlZiQwpObzZoZVY5dGVzN3VYNzI4K1JabTVVMUpoNTRsdzRqZGJLSnZES0pOcmF6d2JQZ3MzV296YXJQbzNOb000c2ZCClZJY3F0WVBHNTBxT2dSSnhjaktpcFBIc21qa21PMlA0ZlVYZkNoMGdjb0VNbU40MnVCMUY5U2grUW9ua3VseEQKRnRqTVBRQmlyZ0hXTm5Mc2YvNkVrSHJ2UDRWMHFrT2JjYmhyNWNUVnJkSHlSR2VJNDRIZXM0R1NlYkF6SEpCcgpFajlleGJKaWdaNXZHZTJId1d1WkpCVFczRzhFNjVqL3BFN2t1WFJJNzRKZzk5ejlQQlFlL05vdGFDNlFTdDNWCllFbGV0Y2RoL0NYYjJlSUl2R0crUlFJREFRQUJvNEhDTUlHL01BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlYKSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRQpHREFXZ0JSL1NBdzNOanBWaGNyeEp6NzlJUG9ZQU12azlEQmZCZ05WSFJFRVdEQldnaWRyY3kxamIyNTBjbTlzCmJHVnlMVzFoYm1GblpYSXVhM1ZpWlhOd2FHVnlaUzF6ZVhOMFpXMkNLMnR6TFdOdmJuUnliMnhzWlhJdGJXRnUKWVdkbGNpNXJkV0psYzNCb1pYSmxMWE41YzNSbGJTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURKMgoxeGNQY2dRQUx6d2M0ZnhGTVdwZnJVVmc3cG10WTg5RWRkaVNvTVQwYXpESXllbll1TTY4a0xNTUNQcE5MYTFlClZ4eEg2TWlWZG1sb0V1ZUVYMFFrUks1akRTbDR1VGM2MHFyai80bmx6UXMvaVhrL3hWMEtEZDFiZlhiaTdQRmQKZ0dqVlN6NTlkVGVtTnB2eU1WbnZvdjhoUUdrR0JvaWpYb2EybzNHT1NNWks4RXVka2hxbnNuY2trMWlzNUo2SQo0K2k2MytpY3FLWGt1bFU5Qy9jNysrdm9jRnBzdndUVkpLbEFkUXVCVmhJNFdrWXNXZ1ZjL1BpWlpNUC9JMjNtCjJNejRqd3dJNUtiZFFKbUkrS3NOTXlsV1hWdkltTnBlUDFjcWFEOWtaNFJsUWcrQUtwTmVOTXBoVEFYYmJQVXgKWGw0bGRYY1o5emIxOVdabG5pUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMkFpNHg1cWNMMG5UcWsxVWx5SjNUSnd3emJTWGdEd1dRUHlVWU9jRWcxc3F5VmRaClBXV0oxbVlxNkV2ZUJWYkNObzZoZVY5dGVzN3VYNzI4K1JabTVVMUpoNTRsdzRqZGJLSnZES0pOcmF6d2JQZ3MKM1dvemFyUG8zTm9NNHNmQlZJY3F0WVBHNTBxT2dSSnhjaktpcFBIc21qa21PMlA0ZlVYZkNoMGdjb0VNbU40Mgp1QjFGOVNoK1Fvbmt1bHhERnRqTVBRQmlyZ0hXTm5Mc2YvNkVrSHJ2UDRWMHFrT2JjYmhyNWNUVnJkSHlSR2VJCjQ0SGVzNEdTZWJBekhKQnJFajlleGJKaWdaNXZHZTJId1d1WkpCVFczRzhFNjVqL3BFN2t1WFJJNzRKZzk5ejkKUEJRZS9Ob3RhQzZRU3QzVllFbGV0Y2RoL0NYYjJlSUl2R0crUlFJREFRQUJBb0lCQVFEUEtRWHdPbjI5QndHWApWSkppWDJXaExFSE1jSG03T1dOcHJBdXBKTDc2SzJsTEs1eml1RVRHT0xDNmswM3pOckFFV3gvUzRNUitPSUx6CmdtSDlSaE1qbmNwOTV4UjFmZ0EvRlVDQ0QvMkhKc2hpNWxVM2VZaVdzTEVEWDRGdDBubTgwZVVOckxFR3lFTUEKMkt1N0EzMWR5TFBIYkRnU1NacFduckx6NHR4amowSHh3ejEyMlY2MmdTZG5abExTdmNRRHlYeDdyZ3FlRTNkaQpCUUx4SGJlYWtMN01wZS9YWGo2cWRlaUxFdE9POC94cjNjOEt0em0vR0djU0hBZ2R1VG96dUdEUUY0RDM0aFVSCmNnSUFlNGhuSFBsaVI1WG9pc3dvV0REdEJYdjlMNDVxclRIWDNzNE5ZSExjK3dWbWVhemZzemJjTHdRSlJTK0YKVVp3TDcxcWhBb0dCQU5pSTVsMHdmdUhqSG1sOVJnSFFPTFJkSEpVeXgvS2ZraFZCYk9NOCtTY21DU29pZ09zbAovcVVlOHZtQ0JPa0tKaTNSQ3hQSkgzL0FIVlJrdi9mam5wOFMvU0dvYTJyeTZtdjhUYkxpb1VxbU9YU25rdXlPCmlVRGlaWmVJNUlwNHNUUlhCSVZzRUxvY0NhSk5LR1Z3MkxCSkEvcnVTalU1aHVFZ05lbmFQNG1OQW9HQkFQOW8KZGQ4QkUwWW1xUGtXdW5wS1NyTnZES01sY0FMdlF2ZTRMeDBZWUhFUndTTUgyMTA2YW8xdGJoby9QTDhhT0dFbQpzMlVPSzdnQUl4SFdWeDE3a3Ribi9BRk9HL1Zuc09BeUJqRnJKQmw4QTZMVTdibDlxTEhSeEtKOCs2Zkp5TUdJCjMrRXp4bW55NzRhS25sVDdZczA4WTNockNvTStiU3BOUjVqWGxlMlpBb0dBU29XYkdybGxBYUxqeFpScXNwY1IKM09rcXZDSjA5QWg5QXptNEd1RFNNdW9CUDNJT2dsOWFLMFBpaFlKODVDTXREcG1pUVZYM3RFVFBFMHQxVWdBUgppRmZGckg3Rk1WS1c0VUU5RUhLMDVmY2RVUXVYSWpqUC9mZXMxU0UwM244NUpYVkpSZzN5Rjhzc2VhSXFZL2NaCmJGcEV0MmlwTzNZbitIVFllVG8yb2NVQ2dZRUF6K1RXZFFQcURXTHdqWGhMcDdrTEh3MFlTei93OGVLUkx4UlQKL1NuWGJwSFdGTTZUWjBwaWF1WVZCZlpOV3Z4YndmQi9lNVZTVHI2RnpVSWJ2TnJXUm1ta1BlZTNhRVRUdTFuYwpvcU1rU2o0Z3M0MEFSOGtaNUV2cjg1c3FPSVJPRGdKOHdWR2tncDhGQ3cyUUhYcFdETnJIMkwvQVdkNFplNkpWCjBmcEJocGtDZ1lCS1pvYVJRZk1mNUxVbzBJcktTSGt0aWt4aTBlNnRNVGFzS0lHWFZMcHpoZjE1NmtyMG5WTE4KSkY2bFdkQ3RnMjlSQTV0Z0JFY25UNDBKUWpSbWdzaGU2UGpqYUtOVXVJN0xnN0Rwc0Eyak9neGFWY1FKT2pwRwo0cWZBVytoaXVVSFJlN1ZzczRnNVpVdmFwYVhjd0ZrQzNOMnorZjBhOVNWbzYrQWR6NDRBaXc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
kind: Secret
metadata:
  name: ks-controller-manager-webhook-cert
  namespace: kubesphere-system
type: Opaque
---
# Source: ks-core-outside-cluster/templates/ks-controller-manager.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-controller-manager
    tier: backend
    version: v3.1.0
  name: ks-controller-manager
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ks-controller-manager
    tier: backend
    # version: v3.1.0
  sessionAffinity: None
  type: ClusterIP
---
# Source: ks-core-outside-cluster/templates/ks-controller-manager.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ks-controller-manager
    tier: backend
    version: v3.1.0
  name: ks-controller-manager
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ks-controller-manager
      tier: backend
      # version: v3.1.0
  template:
    metadata:
      labels:
        app: ks-controller-manager
        tier: backend
        # version: v3.1.0
    spec:
      containers:
      - command:
        - controller-manager
        - --logtostderr=true
        - --leader-elect=true
        - --kubeconfig=/etc/kubeconfig/kubeconfig
        image: kubesphere/ks-controller-manager:v3.1.0
        imagePullPolicy: IfNotPresent
        name: ks-controller-manager
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 30m
              memory: 50Mi
        volumeMounts:
        - mountPath: /etc/kubesphere/
          name: kubesphere-config
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-secret
        - mountPath: /var/lib/kubelet/plugins/
          name: kubelet-plugin
        - mountPath: /etc/localtime
          name: host-time
        - mountPath: /etc/kubeconfig
          name: kubeconfig
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: kubesphere-config
          configMap:
            name: kubesphere-config
            defaultMode: 420
        - name: webhook-secret
          secret:
            defaultMode: 420
            secretName: ks-controller-manager-webhook-cert
        - name: kubelet-plugin
          hostPath:
            path: /var/lib/kubelet/plugins/
            type: DirectoryOrCreate
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
        - name: kubeconfig
          configMap:
            defaultMode: 420
            name: kubeconfig
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 60
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 60
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""
