---
# Source: ks-core/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesphere
  labels:
    helm.sh/chart: ks-core-0.1.0
    app.kubernetes.io/name: ks-core
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v3.1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: ks-core/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesphere
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubesphere
    namespace: kubesphere-system
