---
# Source: ks-core/templates/webhook.yaml
apiVersion: v1
data:
  ca.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lSQUpnTmFMQWFVR0MyMzNmMlR4Q2ZUamt3RFFZSktvWklodmNOQVFFTEJRQXcKSXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0WVc1aFoyVnlMV05oTUI0WERUSXhNRFV5TkRFegpORGsxTVZvWERUTXhNRFV5TWpFek5EazFNVm93SXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0CllXNWhaMlZ5TFdOaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMFRDTVBaeHQKQmF6QnllR21ycm1teEsyd1VrdjFRWDdIODNLYlFEMkNab3lnV0RKL1NzM25INzJwYVd2UWU3SnRtbTVlN1JlRgpoMGNLV3ZWMmlERmphdkNUeVFWUmVPYVMwZDExV3VMTHJETUhjb09TZ3B6UnhVUWN1Z3AvL0I5KzRKUFJ3R0FYCjhLMVk1MkZTQjVZdTlEcUdWZmVKYXV4bzJlM0hwYjd6aXk3ZlRLNGlpa0hucGw3RWRFK3dOUFRac1dDOU5UdVYKeVdQNEZwVWY3aHRLUVpSMmhaUXVYUEQrVXJmYTIvWDlxSnZ2SkhqQkFqbHJjcVJuZkV1S1F0MjdyVzZxcng3Vwo2WW1kL0pVcDlwQS9nM01peGFJL1JVR3JVYUVkNW1taDZNZmNvSHdQcEJ5ZEovbGg0UFN4M01zekNhbmNReXd5CmltZFE0dTY5cVVTUE5RSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUkKS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFJWk1WbDc2M3FhWkFUR1dkbzFkM1pyL3RMdnAzV0I5dkNvNGM5T09HN0IyOEk1VldnOXE2VjJJCmcrOHdrTGVvck1laDBVcllQUTFqWWZzSHBjS0FmZTZJbU1BaXhiTW54MlM5b3ptMnNUcnFaU3l3S21ZWlZXd2IKMHR1WEdJczRkS21yL21kOHdYNmcrYTZHWHg4MmlKaWo2bVNJZVVBdEJqTm5FcFE5bmp1Ly90L200RFc3ZzRGWQpaZ3VGQXp4UG5CWGZObWV1c2hqeUZKTWU4dTUzMStLK3R6NGtibmlVY2hmMkFFU2VCS1lDUUtxV0ZIR0o3Y3RVCjN4Zi96WUJacVpWOC9RMnd6Q01oMlhHZWdSUTRhU1RIamtkRmIwb08wZlRWMzl5NU9FelBwZ0NQZzJDQmt2N1gKQmpzMXdtL0lyQVY4RzJieDhaaU5vUVZjQ3AzOUdBTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlRENDQW1DZ0F3SUJBZ0lRQStUODhJSU1pRCtLSnUzOG0wSVBhREFOQmdrcWhraUc5dzBCQVFzRkFEQWoKTVNFd0h3WURWUVFERXhocmN5MWpiMjUwY205c2JHVnlMVzFoYm1GblpYSXRZMkV3SGhjTk1qRXdOVEkwTVRNMApPVFV5V2hjTk16RXdOVEl5TVRNME9UVXlXakFwTVNjd0pRWURWUVFERXg1U1JVeEZRVk5GTFU1QlRVVXRZV1J0CmFYTnphVzl1TFhkbFltaHZiMnN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ1YKUzdNNm9LY0oyYm9DVExNUzNJUStEeENiWFZZRVY1c29PWlJUd21HSS93TElrM1UrZlM3enNVNlRHUmkyMmptMgo3VFJQNWx3RmJVUnB3WXVTNFlzaUswMCtGQkl5U0NQT1hYbnlaeHQ5YnhiRmJoUFZleDJPR3JLTWM0Wk9XaVhECm5mMTdrWG9sa0FEc2lxREcwZGRHcEdDUTF3LzFjZWNsN2ZzV2xXaUFKd2ZBUFltQTBoKzRoZEErWm5lUWh6UXQKQTBzNWZXRXlnRzNmS3FYczV6aHB2bDIyeXdiL3lVa295SDRSSHU0MnZOSmdsMktnUUVOeE9UcVJpZFBlSkRYYwpxTVNEamFiWTFXY3lMTmU0Mm5lT2xPOVNFRlNsTzNPV2ZsU0FWTlE4UVdYMFRiRkRob05aNXdKMG5KV0JMbnNSClJHWUhlQ3cwd05iVVp2SW8zVDBKQWdNQkFBR2pnYUV3Z1o0d0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1GOEdBMVVkRVFSWQpNRmFDSjJ0ekxXTnZiblJ5YjJ4c1pYSXRiV0Z1WVdkbGNpNXJkV0psYzNCb1pYSmxMWE41YzNSbGJZSXJhM010ClkyOXVkSEp2Ykd4bGNpMXRZVzVoWjJWeUxtdDFZbVZ6Y0dobGNtVXRjM2x6ZEdWdExuTjJZekFOQmdrcWhraUcKOXcwQkFRc0ZBQU9DQVFFQXZtalBmRVhyYkFmcnk5MjVhUVZUNUZldjcvTGhLUmNiUWpkNUhSK1JtZjIyRmZ5agpvUThTRjZBbFJTMEZ5SGhkT1FFcFM5c05OQ3A5Unp1N2k1UGZYYVJrVjZGZU1NQk9MSUVTbUZFcitTYUQ0SDdZCkRKS3p1MVdRS1VUK3NLQVJwTGg4cmEzcXd4eStUaXZDTGFYb2FWWmlSSmwzRTZUNzNlS1NFaXhnTFVRM000cWYKYXVueWVTaXh0OGJIVGZDVlc5YXE3NEQzWU1IWTNZVUVuMlNGLytlME1IYzBPb2tpUEZOdld5YnVjV1hqc0NKeQpoRXFacmpzUWErT0oxQVFIT2lXWDh1V292dDU4SitOd3VubFlPTlRFUnkzaHZWZDRYZ29NaW8zQklId2VKWUltCk9mZFUzR2g1MlJRQVRZdHNGd3NhU1p5WVo1VWpsZXE3cDhIeXZBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbFV1ek9xQ25DZG02QWt5ekV0eUVQZzhRbTExV0JGZWJLRG1VVThKaGlQOEN5Sk4xClBuMHU4N0ZPa3hrWXR0bzV0dTAwVCtaY0JXMUVhY0dMa3VHTElpdE5QaFFTTWtnanpsMTU4bWNiZlc4V3hXNFQKMVhzZGpocXlqSE9HVGxvbHc1MzllNUY2SlpBQTdJcWd4dEhYUnFSZ2tOY1A5WEhuSmUzN0ZwVm9nQ2NId0QySgpnTklmdUlYUVBtWjNrSWMwTFFOTE9YMWhNb0J0M3lxbDdPYzRhYjVkdHNzRy84bEpLTWgrRVI3dU5yelNZSmRpCm9FQkRjVGs2a1luVDNpUTEzS2pFZzQybTJOVm5NaXpYdU5wM2pwVHZVaEJVcFR0emxuNVVnRlRVUEVGbDlFMngKUTRhRFdlY0NkSnlWZ1M1N0VVUm1CM2dzTk1EVzFHYnlLTjA5Q1FJREFRQUJBb0lCQUdJY1NVQXg2eE95SFdiOQplSURnb1pjVzExY0NVMUN2TWF1UmkwUXY3V0RXRk1JekJVMTNmcTl1eWJBcFFmQ0lJSDF5REhxbGE3dTFQc3d4CkFNUVpyQkZjVzNwOFBpa0U5MkxhVXhWVlpOOWRiWjE0NVZmWmZHYXliTHVYLzU3bDV3TlNoQTM4WUVUbkNYUm8KOVpjeXQwSVpLOHlEU0YySDZOc29OV1YxOGlLa2dwd0dHaWlMRTRuTFpoWVFhMmhMSm53S3RtSmY1S0V1TG9qUwptaUw3UWY4bXFGRXRNL29PS3dDTllqRmtCcGJjeXU2VzkrakJlbFBRUkpYeFBJZys2VzZCZTkvKzZmK3pSSXZCCnduaDN3bTdzNG9HMXEyQThicXQrcFZ1YXltcVdBSkgrcktLdkhnVVBvazZLYWFNUis5SVhiRlJmcjhoUDVWSWwKMmlKc3A4RUNnWUVBd0d3b3lmWkVHR2dSUGxNNHdkMm9abi9LbjZwK0xndlJKZk9Pd2tDdG9mYy9pcGx6Mk53WQpzcXJodG9aUUFVUU9vcWVycGRhaWExTWVMNVZ1MVppa1NDd1pVMk1rUWtsZjM5Wjd4MDRzM3BvdENaMGpqWmpzClRmaGl1Q01EeFFaZWxjRnVDQmZuektDU3ZWRHZhSXIxVzFTR05ZZFhYdVlRNkt3Qzl2S0ZJdzBDZ1lFQXhwKzEKbXlYT21zczREMVNLVzRMQmJGRTVPZkxlS0JhMnk4UWlLUjB6cjNJV1dzSjdhSllLa3pmZ3VWVE1qRTIvWGJXZwozK2dwTSs4bjJ5STFSbktiVlNmc2owbzkwcHNIMk5KZW1EQ3l0MGNDU3R3VllZOHM1RWZXNUY2bHNQUHRpcHI0CmxpbytEd2M4Qlo2cTBocUNFNUEyM1NSTnd4dDVrVjdMdDBJQWN1MENnWUVBdTgwVVprRG5weFp5dGV5TmVaRDMKMmNvaG5ZSE9FdXpQblFYQU1GRGw1aTBsSkFXdTdsbXA5VDhZZW9kT01GNFhGcU1rd1AvaGwzUVJBd29LbVllWAoxeVRMTnZxTkdmRDVGTU1HSGJocnpIcVhPRW5ZdUVzblh0WHNxNkRvL2ZQQWZ0TEJyRDZBcXRPUlJCcG8veFNZCmNTSG10dm0zeVZRcjdwcHJiaysycDBVQ2dZRUFrZldMWHhmSlc3YzYyd2tsSTFwVENXWW14NDdSOG1PK3NMN1EKMjZXNTlaUEJHYkVSUHlvRFcyd1VtQnpZczhIdWZzNmFDZkJ4VnRqSVVTQXlSakt5TTBIRGRRajVwV3FIdWEzZQpGYml6bkR0eVU5Q25aYW54TTFBWGVucVRDQlk0MlVKSXF4RWZ5YXRuVURucERieXRHZk5BWGdIdm94RHRwUVlrCmJlYnlyWUVDZ1lCZzV1SEY5WXBxQzFHSERlcW9MVE1uVUZ1WDZJWHhYMUFDczNkUUhOOUZFbDNyRVFOb0ZZUHAKczRhcDVVdDFySHRUMVBGbFJ5SW4yNndwTXZCcWhyK1kxRitnU3JTWVR3dzRtakx3NmZZZGp4TUg3KzJiSnc1MwpEMlNMVG9SYXhtQ21BcEpPeFMrVzJBRE55VmJ6emxoUnY2YnNNWEJUWjBNcW1kNEF3aVhhbHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
kind: Secret
metadata:
  name: ks-controller-manager-webhook-cert
  namespace: kubesphere-system
type: Opaque
---
# Source: ks-core/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: users.iam.kubesphere.io
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lSQUpnTmFMQWFVR0MyMzNmMlR4Q2ZUamt3RFFZSktvWklodmNOQVFFTEJRQXcKSXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0WVc1aFoyVnlMV05oTUI0WERUSXhNRFV5TkRFegpORGsxTVZvWERUTXhNRFV5TWpFek5EazFNVm93SXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0CllXNWhaMlZ5TFdOaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMFRDTVBaeHQKQmF6QnllR21ycm1teEsyd1VrdjFRWDdIODNLYlFEMkNab3lnV0RKL1NzM25INzJwYVd2UWU3SnRtbTVlN1JlRgpoMGNLV3ZWMmlERmphdkNUeVFWUmVPYVMwZDExV3VMTHJETUhjb09TZ3B6UnhVUWN1Z3AvL0I5KzRKUFJ3R0FYCjhLMVk1MkZTQjVZdTlEcUdWZmVKYXV4bzJlM0hwYjd6aXk3ZlRLNGlpa0hucGw3RWRFK3dOUFRac1dDOU5UdVYKeVdQNEZwVWY3aHRLUVpSMmhaUXVYUEQrVXJmYTIvWDlxSnZ2SkhqQkFqbHJjcVJuZkV1S1F0MjdyVzZxcng3Vwo2WW1kL0pVcDlwQS9nM01peGFJL1JVR3JVYUVkNW1taDZNZmNvSHdQcEJ5ZEovbGg0UFN4M01zekNhbmNReXd5CmltZFE0dTY5cVVTUE5RSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUkKS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFJWk1WbDc2M3FhWkFUR1dkbzFkM1pyL3RMdnAzV0I5dkNvNGM5T09HN0IyOEk1VldnOXE2VjJJCmcrOHdrTGVvck1laDBVcllQUTFqWWZzSHBjS0FmZTZJbU1BaXhiTW54MlM5b3ptMnNUcnFaU3l3S21ZWlZXd2IKMHR1WEdJczRkS21yL21kOHdYNmcrYTZHWHg4MmlKaWo2bVNJZVVBdEJqTm5FcFE5bmp1Ly90L200RFc3ZzRGWQpaZ3VGQXp4UG5CWGZObWV1c2hqeUZKTWU4dTUzMStLK3R6NGtibmlVY2hmMkFFU2VCS1lDUUtxV0ZIR0o3Y3RVCjN4Zi96WUJacVpWOC9RMnd6Q01oMlhHZWdSUTRhU1RIamtkRmIwb08wZlRWMzl5NU9FelBwZ0NQZzJDQmt2N1gKQmpzMXdtL0lyQVY4RzJieDhaaU5vUVZjQ3AzOUdBTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    service:
      name: ks-controller-manager
      namespace: kubesphere-system
      path: /validate-email-iam-kubesphere-io-v1alpha2
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: users.iam.kubesphere.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  objectSelector: {}
  rules:
  - apiGroups:
    - iam.kubesphere.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
---
# Source: ks-core/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: network.kubesphere.io
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lSQUpnTmFMQWFVR0MyMzNmMlR4Q2ZUamt3RFFZSktvWklodmNOQVFFTEJRQXcKSXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0WVc1aFoyVnlMV05oTUI0WERUSXhNRFV5TkRFegpORGsxTVZvWERUTXhNRFV5TWpFek5EazFNVm93SXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0CllXNWhaMlZ5TFdOaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMFRDTVBaeHQKQmF6QnllR21ycm1teEsyd1VrdjFRWDdIODNLYlFEMkNab3lnV0RKL1NzM25INzJwYVd2UWU3SnRtbTVlN1JlRgpoMGNLV3ZWMmlERmphdkNUeVFWUmVPYVMwZDExV3VMTHJETUhjb09TZ3B6UnhVUWN1Z3AvL0I5KzRKUFJ3R0FYCjhLMVk1MkZTQjVZdTlEcUdWZmVKYXV4bzJlM0hwYjd6aXk3ZlRLNGlpa0hucGw3RWRFK3dOUFRac1dDOU5UdVYKeVdQNEZwVWY3aHRLUVpSMmhaUXVYUEQrVXJmYTIvWDlxSnZ2SkhqQkFqbHJjcVJuZkV1S1F0MjdyVzZxcng3Vwo2WW1kL0pVcDlwQS9nM01peGFJL1JVR3JVYUVkNW1taDZNZmNvSHdQcEJ5ZEovbGg0UFN4M01zekNhbmNReXd5CmltZFE0dTY5cVVTUE5RSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUkKS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFJWk1WbDc2M3FhWkFUR1dkbzFkM1pyL3RMdnAzV0I5dkNvNGM5T09HN0IyOEk1VldnOXE2VjJJCmcrOHdrTGVvck1laDBVcllQUTFqWWZzSHBjS0FmZTZJbU1BaXhiTW54MlM5b3ptMnNUcnFaU3l3S21ZWlZXd2IKMHR1WEdJczRkS21yL21kOHdYNmcrYTZHWHg4MmlKaWo2bVNJZVVBdEJqTm5FcFE5bmp1Ly90L200RFc3ZzRGWQpaZ3VGQXp4UG5CWGZObWV1c2hqeUZKTWU4dTUzMStLK3R6NGtibmlVY2hmMkFFU2VCS1lDUUtxV0ZIR0o3Y3RVCjN4Zi96WUJacVpWOC9RMnd6Q01oMlhHZWdSUTRhU1RIamtkRmIwb08wZlRWMzl5NU9FelBwZ0NQZzJDQmt2N1gKQmpzMXdtL0lyQVY4RzJieDhaaU5vUVZjQ3AzOUdBTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: ks-controller-manager
        namespace: kubesphere-system
        path: /validate-network-kubesphere-io-v1alpha1
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: validating-network.kubesphere.io
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    objectSelector: {}
    rules:
      - apiGroups:
          - network.kubesphere.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - ippools
        scope: '*'
    sideEffects: None
    timeoutSeconds: 30
---
# Source: ks-core/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: resourcesquotas.quota.kubesphere.io
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lSQUpnTmFMQWFVR0MyMzNmMlR4Q2ZUamt3RFFZSktvWklodmNOQVFFTEJRQXcKSXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0WVc1aFoyVnlMV05oTUI0WERUSXhNRFV5TkRFegpORGsxTVZvWERUTXhNRFV5TWpFek5EazFNVm93SXpFaE1COEdBMVVFQXhNWWEzTXRZMjl1ZEhKdmJHeGxjaTF0CllXNWhaMlZ5TFdOaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMFRDTVBaeHQKQmF6QnllR21ycm1teEsyd1VrdjFRWDdIODNLYlFEMkNab3lnV0RKL1NzM25INzJwYVd2UWU3SnRtbTVlN1JlRgpoMGNLV3ZWMmlERmphdkNUeVFWUmVPYVMwZDExV3VMTHJETUhjb09TZ3B6UnhVUWN1Z3AvL0I5KzRKUFJ3R0FYCjhLMVk1MkZTQjVZdTlEcUdWZmVKYXV4bzJlM0hwYjd6aXk3ZlRLNGlpa0hucGw3RWRFK3dOUFRac1dDOU5UdVYKeVdQNEZwVWY3aHRLUVpSMmhaUXVYUEQrVXJmYTIvWDlxSnZ2SkhqQkFqbHJjcVJuZkV1S1F0MjdyVzZxcng3Vwo2WW1kL0pVcDlwQS9nM01peGFJL1JVR3JVYUVkNW1taDZNZmNvSHdQcEJ5ZEovbGg0UFN4M01zekNhbmNReXd5CmltZFE0dTY5cVVTUE5RSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUkKS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFJWk1WbDc2M3FhWkFUR1dkbzFkM1pyL3RMdnAzV0I5dkNvNGM5T09HN0IyOEk1VldnOXE2VjJJCmcrOHdrTGVvck1laDBVcllQUTFqWWZzSHBjS0FmZTZJbU1BaXhiTW54MlM5b3ptMnNUcnFaU3l3S21ZWlZXd2IKMHR1WEdJczRkS21yL21kOHdYNmcrYTZHWHg4MmlKaWo2bVNJZVVBdEJqTm5FcFE5bmp1Ly90L200RFc3ZzRGWQpaZ3VGQXp4UG5CWGZObWV1c2hqeUZKTWU4dTUzMStLK3R6NGtibmlVY2hmMkFFU2VCS1lDUUtxV0ZIR0o3Y3RVCjN4Zi96WUJacVpWOC9RMnd6Q01oMlhHZWdSUTRhU1RIamtkRmIwb08wZlRWMzl5NU9FelBwZ0NQZzJDQmt2N1gKQmpzMXdtL0lyQVY4RzJieDhaaU5vUVZjQ3AzOUdBTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: ks-controller-manager
        namespace: kubesphere-system
        path: /validate-quota-kubesphere-io-v1alpha2
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: resourcesquotas.quota.kubesphere.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
